packages:
  - 'packages/*'
  - 'apps/*'
  - 'examples'

strictPeerDependencies: false

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - oxlint
  - oxfmt
  - oxlint-tsgolint
  - '@oxlint/*'
  - '@oxfmt/*'
  - '@oxlint-tsgolint/*'

catalog:
  typescript: ^6.0.3

  vite: ^8.0.14
  react: ^19.2.6
  react-dom: ^19.2.6
  '@types/react': ^19.2.15
  '@types/react-dom': ^19.2.3
  '@types/node': ^25.9.1
  vitest: ^4.1.7
  '@vitejs/plugin-react': ^6.0.2
  vite-plugin-dts: ^5.0.1
  playwright: ^1.60.0
  '@vitest/browser': ^4.1.7
  '@vitest/browser-playwright': ^4.1.7
  oxlint: ^1.67.0
  oxfmt: ^0.52.0
  oxlint-tsgolint: ^0.23.0
  tiny-invariant: ^1.3.3
  '@testing-library/react': ^16.3.2
  '@testing-library/jest-dom': ^6.9.1
  '@microsoft/api-extractor': ^7.58.7
  jsdom: ^29.1.1
  knip: ^6.14.2
  '@ladle/react': ^5.1.1
