packages:
  - 'packages/*'
  - 'apps/*'
  - 'examples'

strictPeerDependencies: false

catalog:
  typescript: ^6.0.3

  vite: ^8.0.14
  react: ^19.2.6
  react-dom: ^19.2.6
  '@types/react': ^19.2.15
  '@types/react-dom': ^19.2.3
  '@types/node': ^25.9.1
  vitest: ^4.1.7
  '@vitejs/plugin-react': ^6.0.2
  vite-plugin-dts: ^5.0.1
  playwright: ^1.60.0
  '@vitest/browser': ^4.1.7
  '@vitest/browser-playwright': ^4.1.7
