packages:
  - 'packages/*'
  - 'apps/*'
  - 'examples'

strictPeerDependencies: false

catalog:
  typescript: ^5.9.3

  vite: ^7.3.1
  react: ^19.2.4
  react-dom: ^19.2.4
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@types/node': ^25.3.3
  vitest: ^4.0.18
  '@vitejs/plugin-react': ^5.1.4
  vite-plugin-dts: ^4.5.4
  playwright: ^1.58.2
  '@vitest/browser': ^4.0.18
  '@vitest/browser-playwright': ^4.0.18
