import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  guidesSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
  virtuosoApiSidebar: [
    {
      type: 'category',
      collapsible: false,
      label: 'Virtuoso API',
      link: {
        type: 'doc',
        id: 'virtuoso-api/index',
      },
      items: require('./docs/virtuoso-api/typedoc-sidebar.cjs'),
    },
  ],
  messageListApiSidebar: [
    {
      type: 'category',
      collapsible: false,
      label: 'Virtuoso Message List API',
      link: {
        type: 'doc',
        id: 'virtuoso-message-list-api/index',
      },
      items: require('./docs/virtuoso-message-list-api/typedoc-sidebar.cjs'),
    },
  ],
  /*
  messageListApiSidebar: [
    { type: "autogenerated", dirName: "virtuoso-message-list-api" },
  ],
  */
}

export default sidebars
