import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'
import engineSidebar from './docs/virtuoso-reactive-engine-api/typedoc-sidebar'
import { SidebarItemConfig } from '@docusaurus/plugin-content-docs/src/sidebars/types.js'

const engineSidebarItems = engineSidebar.items as SidebarItemConfig[]
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  guidesSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
  virtuosoApiSidebar: [
    {
      type: 'category',
      collapsible: false,
      label: 'Virtuoso API',
      link: {
        type: 'doc',
        id: 'virtuoso-api/index',
      },
      items: require('./docs/virtuoso-api/typedoc-sidebar.cjs'),
    },
  ],
  messageListApiSidebar: [
    {
      type: 'category',
      collapsible: false,
      label: 'Virtuoso Message List API',
      link: {
        type: 'doc',
        id: 'virtuoso-message-list-api/index',
      },
      items: require('./docs/virtuoso-message-list-api/typedoc-sidebar.cjs'),
    },
  ],
  masonryApiSidebar: [
    {
      type: 'category',
      collapsible: false,
      label: 'Virtuoso Masonry API',
      link: {
        type: 'doc',
        id: 'virtuoso-masonry-api/index',
      },
      items: require('./docs/virtuoso-masonry-api/typedoc-sidebar.cjs'),
    },
  ],
  reactiveEngineSidebar: [
    {
      type: 'category',
      collapsible: false,
      label: 'Reactive Engine',
      link: {
        type: 'doc',
        id: 'virtuoso-reactive-engine-api/index',
      },
      items: [
        ...engineSidebarItems.slice(0, -1),

        {
          type: 'doc',
          // @ts-ignore
          id: engineSidebarItems.at(-1).items[0].id,
          label: 'API Reference',
        },
      ],
    },
  ],
  /*
  messageListApiSidebar: [
    { type: "autogenerated", dirName: "virtuoso-message-list-api" },
  ],
  */
}

export default sidebars
