name: CI
on:
  push:
    branches: [ "main", "v5" ]
  pull_request:
    branches: [ "main", "v5" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      USE_SSH: true
      GIT_USER: petyosi
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Git config user
        uses: snow-actions/git-config-user@v1.0.0
        with:
          name: Virtuoso CI
          email: petyo+ci@virtuoso.dev
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Rush rebuild
        run: node common/scripts/install-run-rush.js rebuild --verbose --production
      - name: Rush publish
        run: node common/scripts/install-run-rush.js publish --apply --target-branch v5 --publish --registry https://registry.npmjs.org/ --npm-auth-token "$NPM_TOKEN" --add-commit-details
